
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sugandha
 */
public class expenseEntry extends javax.swing.JInternalFrame {
    /**
     * Creates new form incomeEntry
     */
    String username;
    Connection x;
    JDesktopPane desktop;
    public expenseEntry(String username,Connection x,JDesktopPane desktop) {
        initComponents();
        this.username=username;
        this.x=x;
     fillLname();
        this.desktop=desktop;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combolname = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(240, 52, 52));

        jPanel2.setBackground(new java.awt.Color(1, 50, 67));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ledger Name To Make Entry");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Ledger From List");

        combolname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combolname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ledger" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("OR");

        btnsearch.setBackground(new java.awt.Color(0, 181, 240));
        btnsearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnsearch)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(combolname, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel3)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combolname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search Expense Ledger ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        String l_name=txtlname.getText();
        if(l_name.trim().length()==0 && combolname.getSelectedIndex()==0 )
        {
            JOptionPane.showMessageDialog(this,"Please enter ledger name");
        }
        else if(l_name.trim().length()>0 && combolname.getSelectedIndex()>0)
        {
            JOptionPane.showMessageDialog(this,"Please proceed with either of the two options");
        }
        else if(l_name.trim().length()>0 && combolname.getSelectedIndex()==0)
        {
               String lname=txtlname.getText();  
               String type="Expense";
   
     try
        {
        
                String q="select * from accountHead where username=? and l_name=? and type=?";
                PreparedStatement y=x.prepareStatement(q);
                y.setString(1,username);
              y.setString(2,l_name);
              y.setString(3,type);
              
                
                ResultSet rs=y.executeQuery();
                String Lname,username,lcode,Type;

                if(rs.next())
                {
                 Lname=rs.getString("l_name");
                 username=rs.getString("username");
                 lcode=rs.getString("l_code");
                 Type=rs.getString("type");
            makeExpenseEntry mie=new makeExpenseEntry(username,x,lcode,Lname);
           this.moveToBack();
            mie.moveToFront();
            
            mie.setVisible(true);
            mie.pack();
   
            desktop.add(mie);
            
                }
            else
                {
                JOptionPane.showMessageDialog(this, "No ledger found \n Select from list \n or make a new one");
                }
                y.close();
                   
            
            
        }
     catch(Exception ex)
     {
        JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();  
     }
     
     
        }
        else if(l_name.trim().length()==0 && combolname.getSelectedIndex()>0)
        {
            try {
                lnameData l=(lnameData)combolname.getSelectedItem();
                String lcode=l.index;
                String type="Expense";
                String q="select * from accountHead where username=? and l_code=? and type=?";
                PreparedStatement y=x.prepareStatement(q);
                y.setString(1, username);
                y.setString(2, lcode);
                y.setString(3,type);
               System.out.println(lcode);
                
                 ResultSet rs=y.executeQuery();
                String name,username,code,Type;

                if(rs.next())
                {
                 name=rs.getString("l_name");
                 username=rs.getString("username");
                 code=rs.getString("l_code");
                 Type=rs.getString("type");
            makeExpenseEntry mie=new makeExpenseEntry(username,x,code,name);
            
            mie.setVisible(true);
            mie.pack();
            //mie.setTitle(txtlname.getText());
            desktop.add(mie);
            
                }
            else
                {
                JOptionPane.showMessageDialog(this, "No ledger found \n Select from list \n or make a new one");
                }
                y.close();
                
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(this,ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnsearchActionPerformed
void fillLname()
{
    try
    {
        String type="Expense";
        String q="Select * from accountHead where username=? and type=? order by l_name";
        PreparedStatement y=x.prepareStatement(q);
        y.setString(1,username);
        y.setString(2,type);
        
        ResultSet rs=y.executeQuery();
        String Type,user;
        while(rs.next())
        {
            lnameData ld=new lnameData();
           ld.name=rs.getString("l_name");
           ld.index=rs.getString("l_code");
            combolname.addItem(ld);
        }
        
    }
    catch(Exception ex)
    {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox combolname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtlname;
    // End of variables declaration//GEN-END:variables
}
