import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sugandha
 */

public class mainFrame extends javax.swing.JFrame {
String username,email;
Connection x;
    /**
     * Creates new form mainFrame
     */
    public mainFrame(String username, Connection x, String email) {
        initComponents();
        this.username=username;
        this.x=x;
        this.email=email;
        Toolkit tk=Toolkit.getDefaultToolkit();
        int w=(int)tk.getScreenSize().getWidth();
        int y=(int)tk.getScreenSize().getHeight();
        this.setSize(w,y);
       
       
     
       
    
       
     
       
       
       
       
       
       
       
       
       
       
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPaneBG1 = new desktopPaneBG();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(240, 52, 52));

        jMenu1.setText("User");

        jMenuItem2.setText("Change Password");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ledger");

        jMenuItem5.setText("Income");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Expense");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem9.setText("View Ledgers");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Entry");

        jMenuItem7.setText("Income");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem1.setText("Expense");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem8.setText("View All");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Monthly");

        jMenuItem10.setText("Electricity ");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("Fees");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem12.setText("Salary");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuItem13.setText("Monthly EMI");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPaneBG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPaneBG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        changePassword cp=new changePassword(username,x,email);
            Dimension desktopSize = desktopPaneBG1.getSize();
Dimension jInternalFrameSize = cp.getSize();
cp.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        cp.setVisible(true);
        cp.pack();
        desktopPaneBG1.add(cp);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //login1 lg=new login1();
        login1 lg= new login1();
lg.setVisible(true);
lg.pack();
lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         try
      {
        x.close();
      }
      catch(Exception ex)
      {
         JOptionPane.showMessageDialog(this,ex.getMessage());
      }
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        createNew cn =new createNew(username,x);
            Dimension desktopSize = desktopPaneBG1.getSize();
Dimension jInternalFrameSize = cn.getSize();
cn.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        cn.setVisible(true);
        cn.pack();
        desktopPaneBG1.add(cn);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
expense en=new expense(username,x);
    Dimension desktopSize = desktopPaneBG1.getSize();
Dimension jInternalFrameSize = en.getSize();
en.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
en.setVisible(true);
en.pack();
desktopPaneBG1.add(en);
       
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
  allHeads ie=new allHeads(username,x,desktopPaneBG1);
            Dimension desktopSize = desktopPaneBG1.getSize();
Dimension jInternalFrameSize = ie.getSize();
ie.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        
        ie.setVisible(true);
        ie.pack();
        desktopPaneBG1.add(ie);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        incomeEntry ie=new incomeEntry(username,x,desktopPaneBG1);
            Dimension desktopSize = desktopPaneBG1.getSize();
Dimension jInternalFrameSize = ie.getSize();
ie.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        
        ie.setVisible(true);
        ie.pack();
        desktopPaneBG1.add(ie);
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        expenseEntry ie=new expenseEntry(username,x,desktopPaneBG1);
            Dimension desktopSize = desktopPaneBG1.getSize();
Dimension jInternalFrameSize = ie.getSize();
ie.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        
        ie.setVisible(true);
        ie.pack();
       desktopPaneBG1.add(ie);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        Electricity ie=new Electricity(username,x);
            Dimension desktopSize = desktopPaneBG1.getSize();
Dimension jInternalFrameSize = ie.getSize();
ie.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        
        ie.setVisible(true);
        ie.pack();
        desktopPaneBG1.add(ie);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
          Fees ie=new Fees(username,x);
              Dimension desktopSize = desktopPaneBG1.getSize();
Dimension jInternalFrameSize = ie.getSize();
ie.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        
        ie.setVisible(true);
        ie.pack();
       desktopPaneBG1.add(ie);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
          Salary ie=new Salary(username,x);
              Dimension desktopSize = desktopPaneBG1.getSize();
Dimension jInternalFrameSize = ie.getSize();
ie.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        
        ie.setVisible(true);
        ie.pack();
        desktopPaneBG1.add(ie);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
          EMI ie=new EMI(username,x);
              Dimension desktopSize = desktopPaneBG1.getSize();
Dimension jInternalFrameSize = ie.getSize();
ie.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        
        ie.setVisible(true);
        ie.pack();
        desktopPaneBG1.add(ie);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        viewAccounts1 va=new viewAccounts1(username,x);
    Dimension desktopSize = desktopPaneBG1.getSize();
Dimension jInternalFrameSize = va.getSize();
va.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
va.setVisible(true);
va.pack();
desktopPaneBG1.add(va);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Date g=new Date();
               SimpleDateFormat h=new SimpleDateFormat("MM-YYYY");
               String cmon=h.format(g);
               
           
               String sd1[]=cmon.split("-");
                String sdate=01+"-"+sd1[0]+"-"+sd1[1]; 
                 String edate=15+"-"+sd1[0]+"-"+sd1[1];
           try
           {
               
                 String name="";
               name.equalsIgnoreCase("Electricity");
                 
               String v3="select * from accountHead where l_name=? and username=? and type=?";
               PreparedStatement y3=x.prepareStatement(v3);
               ResultSet ry=y3.executeQuery();
               String a1;
               while(ry.next())
               {
               a1=ry.getString("l_code");
                
                   String v="select * from headEntry where l_code=? and str_to_date(date,\"%d-%m-%Y\") between str_to_date(?,\"%d-%m-%Y\") and str_to_date(?,\"%d-%m-%Y\") and paid='YES'and username=?";
                   
                   PreparedStatement y1=x.prepareStatement(v);
                    y1.setString(1,a1);
                   y1.setString(2,sdate);
                   y1.setString(3,edate);
                   y1.setString(4, username);
                   ResultSet rx=y1.executeQuery();
                   if(!rx.next())
                   {
                        String subject="Expense to be paid";
                        String message="Welcome to DayBook, it is to notify that you haven't paid your monthly electricity bill. Please pay it as soon as possible. For any further queries you can reply to this mail.";
                        sendMail.sendEmail(email, subject, message);
               
                       JOptionPane.showMessageDialog(this,"Please pay your monthly electricity");
                   
                   }}
               
               String lname="";
               lname.equalsIgnoreCase("Fees");
                 
               String v4="select * from accountHead where l_name=? and username=? and type=?";
               PreparedStatement y4=x.prepareStatement(v4);
               ResultSet ry1=y4.executeQuery();
               String a2;
               while(ry1.next())
               {
               a2=ry1.getString("l_code");
                   String v1="select * from headEntry where l_code=? and str_to_date(date,\"%d-%m-%Y\") between str_to_date(?,\"%d-%m-%Y\") and str_to_date(?,\"%d-%m-%Y\") and paid='YES'and username=?";
                   
                   PreparedStatement y2=x.prepareStatement(v1);
                   y2.setString(1,a2);
                   y2.setString(2,sdate);
                   y2.setString(3,edate);
                   y2.setString(4, username);
                   ResultSet rx1=y2.executeQuery();
                   if(!rx1.next())
                   {
                       
                       String subject="Expense to be paid";
                        String message="Welcome to DayBook, it is to notify that you haven't paid your monthly Fee bill. Please pay it as soon as possible. For any further queries you can reply to this mail.";
                         sendMail.sendEmail(email, subject, message);
                       JOptionPane.showMessageDialog(this,"Please pay your monthly fees");
                   
                   }
                    
               } 
                   
               } 
           
           catch (Exception ex) {
               ex.printStackTrace();
                   JOptionPane.showMessageDialog(this,ex.getMessage());
                   
               }
           
       
           try{
               String type="Expense";
               String q1="select * from headEntry where username=? and type=? ";
               PreparedStatement y1=x.prepareStatement(q1);
               
               
               y1.setString(1,username);
               y1.setString(2,type);
               
               
               ResultSet rs1 = y1.executeQuery();
               
//               System.out.println(y1);
              Date i=new Date();
               SimpleDateFormat sd=new SimpleDateFormat("MM");
               String cmonth=sd.format(i);
               Double a,sum=0.0;
               String n1;
               while (rs1.next()) {
                   
                  n1=rs1.getString("date"); 
//                  System.out.println(n1);
                  String mx[]=n1.split("-");
                  String month=mx[1];
//                  Date de=sd.parse(n1);
                   a = Double.valueOf(rs1.getString("amount"));
                   sum+=a;
               
               if(sum>=5000)
               {
               
                    if(Integer.parseInt(cmonth)==(Integer.parseInt(month)+01))
                   {
                  
                        String subject="Expense to be paid";
                        String message="Welcome to DayBook, it is to notify that you have exceeded your monthly expenses. Please keep track of your expenses or increase your limit. For any further queries you can reply to this mail.";
                         sendMail.sendEmail(email, subject, message);
                       JOptionPane.showMessageDialog(this,"Please pay your monthly fees");JOptionPane.showConfirmDialog(this,"You have exceeded your Monthly Limit i.e. "+sum,"Do you want to continue?",JOptionPane.YES_NO_OPTION);
               }
               
               }
               }
               
           } 
       catch (Exception ex) {
           ex.printStackTrace();
         JOptionPane.showMessageDialog(this,ex.getMessage());
                
            }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new mainFrame(username,x).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private desktopPaneBG desktopPaneBG1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
